workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: 16.2
    scripts:

      - name: Clean Flutter build
        script: |
          flutter clean
      - name: Clean and reset Pods
        script: |
          cd ios
          pod cache clean --all
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Create .ipa file
        script: |
          cd ios
          mkdir -p Payload
          cp -r ../build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

    artifacts:
      - ios/app.ipa
    publishing:
      email:
        recipients:
          - ramosmark833@gmail.com
