workflows:
  my flow:
    name: "iOS Build"
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
      cocoapods: default

      BUNDLE_ID: "com.example.smartbin"

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - ios/Flutter/*.dSYM.zip
      - build/**/*.log

    publishing:
      email:
        recipients:
          - "ramos.marklawrence.03042002@gmail.com"
        notify:
          success: true
          failure: false