# Uncomment this line to define a global platform for your project
platform :ios, '13.0'


# Ensure this path is correct
flutter_root = File.expand_path('..', Dir.pwd) + '/flutter'
unless File.exist?(flutter_root)
  raise "Flutter SDK not found at: #{flutter_root}"
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end


# Ensure Flutter is properly configured
require File.expand_path(File.join('..', 'flutter', 'packages', 'flutter_tools', 'bin', 'podhelper'))
